@mkurnikov remove Security and SecurityStorage, update to Move 1.2
pontem-network/move-stdlib pull request #12
Opened 2021-05-13 10:39 UTC by mkurnikov

2021-05-19 23:08 UTC, borispovod requested changes
Need fixes, see my comments.
Also, we need to adopt new Diem's standard library instead of using our own, but for now it's ok.

2021-05-19 23:08 UTC, borispovod commented on modules/pontem.move
> +    native public fun deposit_native<Token: store>(address: &signer, amount: u128): Pontem::T<Token>;
Just T<Coin>?

2021-05-19 23:08 UTC, borispovod commented on modules/pontem.move
> +    native public fun deposit_native<Token: store>(address: &signer, amount: u128): Pontem::T<Token>;
`T<Coin>`

2021-05-19 23:08 UTC, borispovod commented on modules/pontem.move
> +    native public fun withdraw_native<Token: store>(address: &signer, balance: Pontem::T<Token>);
Same here?

2021-05-25 23:58 UTC, borispovod requested changes
Look at events please, otherwise seems fine. 
And run pipelines with new dove version, so it will pass tests.

2021-05-25 23:58 UTC, borispovod commented on modules/Event.move
> +module Event {
We have custom event logic in Pontem, does @RIg410 know about event changes?

2021-05-26 00:01 UTC, borispovod commented on old_modules/u256.move
> +address 0x1 {
why needs old_modules?

2021-05-26 11:47 UTC, mkurnikov commented on modules/Event.move
> +module Event {
I asked him, he said that we support both versions, so I've added one from Diem. Should I change it into our simpler one?

2021-05-27 08:45 UTC, fzzr- commented on modules/Сoins.move
> +/// Deprecated!!!!
Explain the reasons for deprecation please.

2021-05-28 13:13 UTC, fzzr- approved these changes

2021-05-28 14:50 UTC, fzzr- commented
@borispovod [This](https://github.com/pontem-network/move-stdlib/pull/12#pullrequestreview-668456206) is resolved now but unfortunately I can't mark it as resolved. So I'll merge it now.

2021-05-28 14:53 UTC, merged